### ISSUE TITLE
Design

### ISSUE THREAD

**Issue by mxstbr** [pure-ui/styleguide#10]
We need a designer. If this wants to be a success, it needs to be easily useable, feel great and look amazing and well thought out.

Drop the plugin into your webpack configuration, tell us where your components are and we'll make you the most easily usable and most beautiful styleguide you've ever seen. That's how it should be.

**Comment by nikgraf** [comment]
Agreed, I have a few potential candidates, but I suggest to move it a bit further until we ask them.

**Comment by jantimon** [comment]
Agreed - right now the project is very technical. As soon as we got a working example out of several components it's way easier to understand and design.

**Comment by nikgraf** [comment]
We already have a couple people contributing to design. Let's open up more focused issues.
