### ISSUE TITLE
Add an example using React-Look

### ISSUE THREAD

**Issue by nikgraf** [pure-ui/styleguide#140]
https://github.com/rofrischmann/react-look

**Comment by mxstbr** [comment]
Implemented in #171, but not merged.

`react-look` needs the root component of the app to be wrapped in a `LookRoot` component. This would only be possible in the ReactPlugin if we add a special case for it, which imo isn't worth the added complexity. (Who thought that was a good idea anyway…)

Closing for now, might reopen again at a later date if more people start using it.
