### ISSUE TITLE
Filter input doesn't act like a search input

### ISSUE THREAD

**Issue by okonet** [pure-ui/styleguide#195]
1. Focus "filter" input and start typing to filter components
1. Press ESC to clear the search (default `<input type="search" />` behavior)

See how sidebar is hidden instead of resetting input value.

Also, it would be great to have the standard appearance with "reset" button (×) on the right side for this input to keep the affordance.

**Comment by nikgraf** [comment]
sounds good, wanna take it @okonet?

**Comment by okonet** [comment]
I could try. It might conflict with #185 though.

**Comment by mxstbr** [comment]
It shouldn't if you do `evt.stopPropagation()`!

**Comment by okonet** [comment]
Since this is the built in feature, I'd opt-in for filtering the event handling out from the custom handler #185  has introduced as re-implementing this behavior on my own for the `input`.

**Comment by nikgraf** [comment]
👍
