### ISSUE TITLE
404 page in client

### ISSUE THREAD

**Issue by mxstbr** [pure-ui/styleguide#198]
When opening the URL of a component that doesn't exist (e.g. `localhost:8080/styleguide/#/some/blabla/not/a/component`) then you're only greeted with a white page. We should add a 404 page by adding this route to `client/client.js` after all component routes:

```JSX
<Route path="*" component={FourOhFour} />
```

Where `FourOhFour` refers to a component in the client.

**Comment by nikgraf** [comment]
@mxstbr can we close this?

**Comment by mxstbr** [comment]
Yessir!
