### ISSUE TITLE
Improve lazy loading

### ISSUE THREAD

**Issue by jantimon** [pure-ui/styleguide#20]
Right now there are two big issues with the lazy loading:

`load` will load the same component over and over again (we need to store which components have already started loading)
https://github.com/pure-ui/styleguide/commit/1c1a4d4ffcbd5eca9c49ee68788e569a50a2943f#diff-5cc289fea71faec951e6ddaff037fbbfR5

the client-api should move to the client folder - so we can use es6 and have the client code in one place

**Comment by mxstbr** [comment]
Don't we already have that stored in the `cache`? It should be sufficient to wrap the whole content of `load`:

```JS
cache: {},
load: function load(name) {
  if (!this.cache[name]) {
    // load contents 
  }
}
```

> I can't try this right now because #19 broke all the examples and I have yet to figure out why. Right now `npm run client:dev` is the only thing that works. /cc @nikgraf

**Comment by jantimon** [comment]
The idea is good however if the script loading takes a moment cache will still be empty and calling load again will start a second script loading.

**Comment by mxstbr** [comment]
@jantimon let's have a second variable next to cache called loadStarted and set loadStarted[name] to true. Then we can check it inside the load function

**Comment by jantimon** [comment]
Sounds good

**Comment by nikgraf** [comment]
not relevant anymore as we changed the architecture …
