### ISSUE TITLE
Examples syntax

### ISSUE THREAD

**Issue by nikgraf** [pure-ui/styleguide#23]
In PR https://github.com/pure-ui/styleguide/pull/22 I added 2 more advanced example.

I think by introducing the opportunity to run code before rendering the JSX we can cover all sensible cases a component create might want to demonstrate.

I see 3 options:

1. exampleFixtures is not a valid jsdoc tag, but I think that's not too big of a deal
2. we could have an separate `@exampleFixture` for each `@example`
3. As an alternative we could drop the `@exampleFixtures` and identify if the code is JSX and wrap or return the full component if not. e.g.

```
import React from 'react';
import { List } from 'immutable';

/**
 * ImmutableList component
 *
 * @example
 * import { List } from 'immutable';
 * import React from 'react';
 * const list = List([1,2,3]);
 * <ImmutableList data={ list } />
 * @example
 * import { List } from 'immutable';
 * import React from 'react';
 * const emptyList = List();
 * <ImmutableList data={ emptyList } />
 */
export default ({ data = List() }) => ((
  <ul>
    { data.map((item) => (<li>{item}</li>))}
    { data.size === 0 ? 'This list is empty' : '' }
  </ul>
));
```

Version 3 sounds like the most flexible one and easy to graps, but leads to more code in the docs. What would you prefer?

**Comment by mxstbr** [comment]
I think the third option is fine.

**Comment by mxstbr** [comment]
@JedWatson just had a brilliant ideas for examples, instead of putting them in the comments you have an `add` function you can import:

```JS
import React, { Component } from 'react';
import { add } from 'styleguide';

class Button extends Component {
  render() {
    return (
      <button
        className={ "btn " + this.props.disabled ? "btn--disabled" : "" }
      >
        { this.props.children }
      </button>
    );
  }
}

add('Default Button', () => {
  <Button>Click me!</Button>
});

add('Disabled Button', () => {
  <Button disabled>Click me!<Button>
});

export default Button;
```

**Pros**

- Fixtures are already there, if you're using ImmutableJS, it'll already be imported
- We don't need to use react-docgen/webpack, this works for everything

**Cons**

???

**Comment by JedWatson** [comment]
@nikgraf @mxstbr aah, nostalgia
