### ISSUE TITLE
Solid props table based on the propTypes 

### ISSUE THREAD

**Issue by nikgraf** [pure-ui/styleguide#41]
There is a pretty cool tool: https://github.com/FormidableLabs/ecology

If they expose the props table as function/component we can simply use theirs. If not we can copy it over to here.

see live example at the bottom: http://victory.formidable.com/docs/victory-label

Might now be the end solution, but way better for now.

**Comment by mxstbr** [comment]
They use https://github.com/FormidableLabs/component-playground for the playground, we could take a look at simply integrating that.

**Comment by nikgraf** [comment]
:+1:
