### ISSUE TITLE
Allow to store & retrieve certain component setups in the local storage.

### ISSUE THREAD

**Issue by nikgraf** [pure-ui/styleguide#43]
I image a user creates a component state that looks interesting. Allow her/him to save this state and it should be loaded next time the user comes back.

I imagine you build a certain state in the form. If you want to save this state for later you should simply be able to.

**Comment by mxstbr** [comment]
Proposal for the state saving:

```JS
// Saved states
{
  'content': {
    'value': 'Click me!'
  },
  'width': {
    'value': 200,
    'options': {
      'min': 50,
      'max': 250
    }
  }
}
```
