### ISSUE TITLE
Unique name for window.components

### ISSUE THREAD

**Issue by mxstbr** [pure-ui/styleguide#5]
Right now, if somebody saves something to `window.components` it overrides our saved components and the styleguide won't work, which is bad. We should specify a more-unique name here, where the chance is low somebody accidentally overrides it. Maybe something like `__STYLEGUIDE_PLUGIN_COMPONENTS_DO_NOT_TOUCH__`?

**Comment by mxstbr** [comment]
Or maybe `__STYLEGUIDE_PLUGIN_INTERNALS_DO_NOT_TOUCH__` as to not tell the users anything about the insides of the object, which might trigger them to try changing it around.

**Comment by jantimon** [comment]
:+1:  `__STYLEGUIDE_PLUGIN_COMPONENTS`
