### ISSUE TITLE
Use [variablename] instead of %%variablename%%

### ISSUE THREAD

**Issue by mxstbr** [pure-ui/styleguide#7]
`[variablename]` seems to be the standard for webpack, so replacing the weird `%%variablename%%` syntax with that might make sense for newcomers to the codebase.

**Comment by mxstbr** [comment]
@jantimon any objections?

**Comment by jantimon** [comment]
good idea to change it. %%name%% was just the first approach to get it working
`[variablename]` is valid javascript and might replace "real" javascript of entry.js so we should probably look for something else.

**Comment by nikgraf** [comment]
agreed @jantimon - any suggestions?

**Comment by jantimon** [comment]
In the end the entry.js is a template - maybe we could precompile it with a lightweight template engine to increase the readability and it's easier to understand that it's just a template for the component entry point.

**Comment by mxstbr** [comment]
What about something like this: http://ejohn.org/blog/javascript-micro-templating/

**Comment by jantimon** [comment]
Can we use `with` together with webpack 2.0?

**Comment by mxstbr** [comment]
What would you use it for here?

**Comment by jantimon** [comment]
The microtemplating and the lodash template (which is based on johns micro templating) use it
