### ISSUE TITLE
Add Test Coverage

### ISSUE THREAD

**Issue by busypeoples** [pure-ui/styleguide#97]

**Comment by busypeoples** [comment]
We will need a strategy here. function.toString() seems to cause troubles in an instanbul context. This will break the propsToVariation function tests. 

https://github.com/gotwarlost/istanbul/issues/310

**Comment by nikgraf** [comment]
@busypeoples 
@neuling had the idea to potential call these function with an apply. This would fix the test and potential avoid context issues on the front-end?!?

**Comment by busypeoples** [comment]
Sounds good. Let's give it try. Avoiding function.toString(), will definitely fix this specific issue. All other tests work out of the box with istanbul.

**Comment by busypeoples** [comment]
I think we can close this issue. All tests run through. @nikgraf
